item {
  id:  1
  name:  'Speed limit (30km/h)'
}

item {
  id:  2
  name:  'Speed limit (50km/h)'
}

item {
  id:  3
  name:  'Speed limit (60km/h)'
}

item {
  id:  4
  name:  'Speed limit (70km/h)'
}

item {
  id:  5
  name:  'Speed limit (80km/h)'
}

item {
  id:  6
  name:  'Speed limit (100km/h)'
}

item {
  id:  7
  name:  'Speed limit (120km/h)'
}

item {
  id:  8
  name:  'No passing'
}

item {
  id:  9
  name:  'No passing for vehicles over 3.5 metric tons'
}

item {
  id:  10
  name:  'Priority road'
}

item {
  id:  11
  name:  'Yield'
}

item {
  id:  12
  name:  'Road work'
}

item {
  id:  13
  name:  'Keep right'
}

